---
volumes:
  postgresql_data: {}

services:

  postgres:
    image: postgres:${POSTGRESQL_VERSION:-18}
    environment:
      POSTGRES_PASSWORD: hackme
    read_only: true
    security_opt:
      - no-new-privileges:true
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql
      - ./configuration/postgres/seeds:/docker-entrypoint-initdb.d
    command: "postgres -c log_statement=all -c log_line_prefix='%t:%r:user=%u,database=%d,app=%a,query_id=%Q:[%p]:'"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/run

  bats:
    build:
      context: ../../
      dockerfile: scripts/localdev/configuration/bats/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: hackme
      PGDATABASE: unittest
    command:
      - /code
    volumes:
      - ../bats:/code
