---
version: "2"

run:
  concurrency: 4
  timeout: 2m
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - err113
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5

  settings:
    gocyclo:
      min-complexity: 35

    revive:
      rules:
        - name: exported
          disabled: true

    lll:
      line-length: 120

  exclusions:
    warn-unused: true
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          # bodyclose reports some false-positives when using a test request recorder
          - bodyclose
          # It's overkill to use `NewRequestWithContext` in tests
          - noctx

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
