---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: {{.Values.postgresUser | b64enc}}  # yamllint disable-line
  password: {{.Values.postgresPassword | b64enc}}  # yamllint disable-line
