---
name: linter
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lint YAML files
        run: yamllint .  # YAML lint is already installed in ubuntu-latest
